version: "3.4"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodejs
    ports:
      - 8080:8080
    logging:
      driver: none

  nodejs:
    build: .
    volumes:
      - ./vanilla.js:/vanilla.js
      # - ./node.js/.env:/nodejsapp/.env
      - ./node.js/store.js:/nodejsapp/store.js
      - ./node.js/binance.js:/nodejsapp/binance.js
      - ./node.js/main.js:/nodejsapp/main.js
    environment:
      REDIS_URL: redis://redis
    entrypoint: nodemon main.js
    scale: 1
    depends_on:
      - redis

  redis:
    image: "redis"
    logging:
      driver: none

  # redjs:
  #   build: ./red.js
  #   ports:
  #     - 6789:6789
  #   volumes:
  #     - ./red.js/red.js:/red.js/red.js
  #   entrypoint: nodemon
  #   scale: 1
